### ISSUE TITLE
Task List for Week Two

### ISSUE THREAD

**Issue by SravanKairamkonda** [SravanKairamkonda/ForgottenVillage#3]
Systems Development
- [x] Player throw
- [x] Fireball collision with enemy
- [x] Fire Ball and player throw mechanism
- [x] Fireball respawn after destroy
- [x] Player Height
- [ ] Enemy idle, walk, death and damage system
